### ISSUE TITLE
SSE调用方式在Android上遇到NetworkOnMainThreadException

### ISSUE THREAD

**Issue by xinyuechen0319** [MetaGLM/zhipuai-sdk-java-v4#10]
在Android设备上执行SSE调用，遇到NetWorkOnMainThreadException，报错日志：

03-05 18:23:32.623 14557 14557 E AndroidRuntime: FATAL EXCEPTION: main
03-05 18:23:32.623 14557 14557 E AndroidRuntime: Process: com.cxy.demo, PID: 14557
03-05 18:23:32.623 14557 14557 E AndroidRuntime: android.os.NetworkOnMainThreadException
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1669)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:431)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:662)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:657)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.OutputStreamSink.write(JvmOkio.kt:56)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:102)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.RealBufferedSink.flush(RealBufferedSink.kt:268)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Writer.rstStream(Http2Writer.kt:135)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Connection.writeSynReset$okhttp(Http2Connection.kt:354)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream.close(Http2Stream.kt:240)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream.cancelStreamIfNecessary$okhttp(Http2Stream.kt:506)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okhttp3.internal.http2.Http2Stream$FramingSource.close(Http2Stream.kt:488)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.ForwardingSource.close(ForwardingSource.kt:32)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.kt:309)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.RealBufferedSource.close(RealBufferedSource.kt:480)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.ForwardingSource.close(ForwardingSource.kt:32)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.RealBufferedSource.close(RealBufferedSource.kt:480)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at okio.RealBufferedSource$inputStream$1.close(RealBufferedSource.kt:173)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:423)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:196)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at java.io.InputStreamReader.close(InputStreamReader.java:199)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at java.io.BufferedReader.close(BufferedReader.java:536)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at com.zhipu.oapi.service.v4.model.ResponseBodyCallback.onResponse(ResponseBodyCallback.java:90)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(Unknown Source:6)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:966)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:293)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at android.app.ActivityThread.loopProcess(ActivityThread.java:10061)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:10050)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-05 18:23:32.623 14557 14557 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1245)

根据堆栈定位到源码错误位置
com.zhipu.oapi.service.v4.model.ResponseBodyCallback.onResponse(ResponseBodyCallback.java:90)

```java
@Override
public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response) {
    ......

    } catch (Throwable t) {
        onFailure(call, t);
    } finally {
        if (reader != null) {
            try {
                reader.close();
            } catch (IOException e) {
		// do nothing
            }
        }
    }
}
```

**Comment by glide-the** [comment]
不支持android
