### ISSUE TITLE
超拟人大模型 这个SDK 的调用有实现吗，貌似没看到

### ISSUE THREAD

**Issue by flyketch** [MetaGLM/zhipuai-sdk-java-v4#11]
> [超拟人大模型](https://open.bigmodel.cn/dev/api#characterglm)

**Comment by flyketch** [comment]
破案了，超拟人大模型暂时只支持V3版本API，该项目基于V4版本构建。

临时解决方案为：自己调用V3接口实现，后续等官方SDK更新吧。

**Comment by blueokanna** [comment]
你可以用 4 的试试，因为那个有System的一项，可以改改试一下
