### ISSUE TITLE
国内有参考spring ai框架集成国内模型吗？

### ISSUE THREAD

**Issue by JanHuber** [MetaGLM/zhipuai-sdk-java-v4#16]
国内有参考spring ai框架集成国内模型吗？

**Comment by JanHuber** [comment]
是不是没有资源投入，sdk封装的层次有点模糊（与spring ai封装的其他模型对比）。

**Comment by glide-the** [comment]
在spring ai这侧的需求我们目前还没跟进，都是广大的开源人员提供的代码，如果您有兴趣欢迎为java技术社区做出贡献
