### ISSUE TITLE
java sdk sse调用 如何主动控制停止推送

### ISSUE THREAD

**Issue by mufeng-jiang** [MetaGLM/zhipuai-sdk-java-v4#18]
sdk version: release-V4-2.0.1

代码已参考sdk testSseInvoke方法，请问如何控制在推送的时候停止推送，类似于GPT输出的时候暂停输出，然后EventStream也会暂停输出；

请问通过什么参数实现，如果可以实现，那tokens是不是也是累计到停止的这一块。

谢谢。

**Comment by glide-the** [comment]
服务端目前不支持，后续计划请关注官网公告
