### ISSUE TITLE
java8,springboot2.7.12中pom.xml中引用这个依赖后，项目无法启动，报错

### ISSUE THREAD

**Issue by tujianjun523** [MetaGLM/zhipuai-sdk-java-v4#2]
报错信息：
java.lang.ClassNotFoundException: kotlinx.coroutines.debug.AgentPremain
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)

**Comment by blueokanna** [comment]
哥们要不试试我的这个？只要是 **JDK 11+** 的版本就行 👍🏼 

简单改一点就可以直接使用，不管哪一种都可以，Github 链接：[ChatGLM-Java-SDK-Version 4](https://github.com/blueokanna/ChatGLM-Java-SDK)

----
欢迎你来 fork 我的项目或者分享我的项目，在这里先谢谢各位，如果有什么使用上的 bug 可以在项目的 issue 发起，我这边会尽可能修复，最后不介意的话也可以给我的项目点个⭐️ (￣▽￣)～■干杯

**Comment by yazong** [comment]
<dependency>
            <groupId>cn.bigmodel.openapi</groupId>
            <artifactId>oapi-java-sdk</artifactId>
            <version>release-V4-2.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.20</version>
        </dependency>


这样可以适配JDK17，你这个错跟我的一样，按我的方式就可以解决。

**Comment by blueokanna** [comment]
>         <dependency>
>             <groupId>cn.bigmodel.openapi</groupId>
>             <artifactId>oapi-java-sdk</artifactId>
>             <version>release-V4-2.0.0</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>org.projectlombok</groupId>
>                     <artifactId>lombok</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.projectlombok</groupId>
>             <artifactId>lombok</artifactId>
>             <version>1.18.20</version>
>         </dependency>
> 
> 
> 这样可以适配JDK17，你这个错跟我的一样，按我的方式就可以解决。

哥们，JDK17不是向下兼容，这个8写的，也就是向下可以使用

**Comment by ahanhana** [comment]
同样遇到了这个问题，ClassNotFoundException: kotlinx.coroutines.debug.AgentPremain，IDEA的Debug启动时会出现，我的解决方案是下载Jar包本地放resource目录后当成本地依赖导入。

**Comment by swansrp** [comment]
idea的问题 
File -> Settings -> Build, Execution, Deployment -> Debugger -> Data Views -> Kotlin -> Disable coroutine agent. 在Disable coroutine agent前勾选后保存即可

**Comment by hggCode** [comment]
jdk8 spirngboot2.5.4 也是一样的报错

**Comment by su-poles** [comment]
> idea的问题 File -> Settings -> Build, Execution, Deployment -> Debugger -> Data Views -> Kotlin -> Disable coroutine agent. 在Disable coroutine agent前勾选后保存即可

此法亲测可以用
