### ISSUE TITLE
调用的function在哪里定义的

### ISSUE THREAD

**Issue by cJieYang** [MetaGLM/zhipuai-sdk-java-v4#20]
下图调用的function在哪里定义的？

**Comment by cJieYang** [comment]
![1](https://github.com/MetaGLM/zhipuai-sdk-java-v4/assets/41616158/a17d75c4-b79a-46ed-9b7e-d1321b8e879b)

**Comment by glide-the** [comment]
sdk做了一版重构，目前我们并没有计划在sdk中实现对外部工具的交互，从POJO转换成工具json。您可以通过外部工具mbknor-jackson-jsonschema实现，一些完整的生态请异步springAI
