### ISSUE TITLE
class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.zhipu.oapi.service.v4.model.ChatMessage 

### ISSUE THREAD

**Issue by ruanrongman** [MetaGLM/zhipuai-sdk-java-v4#26]
reids存储的时候，反序列化出来之后迭代list出现上述错误。

**Comment by glide-the** [comment]
> reids存储的时候，反序列化出来之后迭代list出现上述错误。

这个类目前没有实现序列化，你可以自己定义一些结构，或者查看序列化包"serialization"的处理方式，在objectmapper注册自己的模块

**Comment by glide-the** [comment]
仓库已经支持不需要自己定义序列化
