### ISSUE TITLE
调用成功fastjson  1.2.76转换 有问题

### ISSUE THREAD

**Issue by SunBriad** [MetaGLM/zhipuai-sdk-java-v4#36]
结果返回调用成功，但是打印信息出现下面的内容
200
调用成功
ImageResult(created=null, data=null, error=ChatError(code=500, message=write javaBean error, fastjson version 1.2.76, class io.undertow.servlet.spec.HttpServletRequestImpl, method : getAsyncContext))

**Comment by glide-the** [comment]
不支持这个序列化框架，使用jackson
