### ISSUE TITLE
Java17访问流式接口是会报错吗？

### ISSUE THREAD

**Issue by Dockkkkkkkkk** [MetaGLM/zhipuai-sdk-java-v4#37]
![image](https://github.com/user-attachments/assets/f3cfbc1a-7415-467d-9cc9-d7067f41d507)
我这里的apiSecretKey是可用的，我复制SDK里的示例代码运行也是报错

**Comment by glide-the** [comment]
这个错误看起来是你没正确设置apikey，移步官网的文档查看基础示例
