### ISSUE TITLE
sse-V4：非function调用demo结果存疑

### ISSUE THREAD

**Issue by GiuhubLinZK** [MetaGLM/zhipuai-sdk-java-v4#6]
<img width="1017" alt="Snipaste_2024-02-13_22-32-24" src="https://github.com/zhipuai/zhipuai-sdk-java-v4/assets/118870779/a6a7cbc4-fe33-4e2c-95cc-737185f4d2c7">
作者您好，请问为什么该方法执行之后并没有输出任何结果而只是返回200的状态码呢？

**Comment by ybh-ybh** [comment]
这里缺少了一部分代码。通过debug可以发现，sseModelApiResp.flowable是不为空的。
JSON.toJSONString()无法解析flowable对象。
将【sse-V4：function调用】内的这一部分代码copy过来，就可以发现在控制台能够流式输出回答了
![图片](https://github.com/zhipuai/zhipuai-sdk-java-v4/assets/107842963/aa718a28-ab55-40f4-83b9-438b39a9f7e5)
