### ISSUE TITLE
apiSecret can not be empty

### ISSUE THREAD

**Issue by staticTao** [MetaGLM/zhipuai-sdk-java-v4#7]
model output:{"code":-100,"msg":"invalid param: apiSecret can not be empty","success":false}

请问API_SECRET在哪获取

**Comment by 2235864511** [comment]
将API_SECRET参数去掉即可,demo里面可能是因为忘记去掉了

**Comment by CoderXiaohui** [comment]
新版机制中平台颁发的 API Key 同时包含 “用户标识 id” 和 “签名密钥 secret”，即格式为 {id}.{secret} 。

参考文档：https://open.bigmodel.cn/dev/api#nosdk
![iShot_2024-02-29_17 05 47](https://github.com/zhipuai/zhipuai-sdk-java-v4/assets/17446149/7ead852f-b283-4a61-8a19-d59fe241eaaf)

**Comment by 2235864511** [comment]
Java的SDK 在github里面有人提了MR的合并请求,那里把secret参数已经去了的,你们可以考虑是否合并上去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhipuai/zhipuai-sdk-java-v4"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月29日(星期四) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhipuai/zhipuai-sdk-java-v4] apiSecret can not be empty (Issue #7)





 
新版机制中平台颁发的 API Key 同时包含 “用户标识 id” 和 “签名密钥 secret”，即格式为 {id}.{secret} 。
 
参考文档：https://open.bigmodel.cn/dev/api#nosdk
 iShot_2024-02-29_17.05.47.png (view on web)
